/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yrachid' at '5/17/16 10:43 AM' with Gradle 2.12
 *
 * @author yrachid, @date 5/17/16 10:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
