CREATE TABLE IF NOT EXISTS aeroportos(
    id SERIAL,
    nome VARCHAR,
    identificador VARCHAR,

    CONSTRAINT PK_AEROPORTOS PRIMARY KEY (id),
    CONSTRAINT AK_AEROPORTOS_IDENTIFICADOR UNIQUE(identificador)
);


CREATE TABLE IF NOT EXISTS companhias_aereas (
    id SERIAL,
    nome VARCHAR,
    identificador VARCHAR,

    CONSTRAINT PK_COMPANHIAS_AEREAS PRIMARY KEY (id),
    CONSTRAINT AK_COMPANHIAS_AEREAS_IDENTIFICADOR UNIQUE(identificador)
);
